### ISSUE TITLE
orderby and groupby may cause SQL injection

### ISSUE THREAD

**Issue by JihanZhuang** [twinh/wei#185]
if orderby function get the param like this:
',if(length(database())=20,1,(select 1 from information_schema.tables))'

I suggest those function can just allow '.','_','$' characters and the $order param can be just 'ASC' or 'DESC'

**Comment by twinh** [comment]
`orderBy` and `groupBy` act like the `where` function, you can pass raw sql, eg `where('num > 10')`,

and a use case for `orderBy` to pass raw sql
```php
$userIds = [1, 3, 5];
$users = wei()->user()
    ->orderBy('FIELD(id, ' . implode(', ', $userIds) . ')') // make mysql to return records in given order [1, 3, 5]
    ->findAll(['id' => $userIds]);
```

to avoid `orderBy` injection, you may use
```php
$users = wei()->user();
$sortFields = ['id', 'score']; // or $users->getFields()
if (in_array($req['sort'], $sortFields)) {
    $users->orderBy($req['sort'], $req['order'] == 'asc' ? 'ASC' : 'DESC');
} else {
    $users->desc('id');
}
```

you may also use `asc` or `desc` functions to avoid $order param injection
```
wei()->user()->desc('id');
wei()->user()->asc('id');
```

**Comment by twinh** [comment]
reopen if you have any problems
