### ISSUE TITLE
db部分似乎有内存泄露

### ISSUE THREAD

**Issue by ykjsw** [twinh/wei#186]
用php做驻后台进程，每次查询完毕后都会wei()->db->close() 但dmap-x查到的内存还是一直在增加。

**Comment by twinh** [comment]
你好，`wei()->db->close()` 只是将 PDO 关闭。db 对象，还有前面的查询语句都还记录着（ `wei()->db->getQueries()` 可以获取）是否有可能这个导致内存继续增加。

还有，dmap-x 哪里可以找到的呢？

```php
    /**
     * Close the database connection
     */
    public function close()
    {
        $this->pdo = null;
        $this->isConnected = false;
    }
```

看能否这样操作

1. 将整个 db 对象销毁

```
wei()->remove('db');
```

2. 定时重启

**Comment by ykjsw** [comment]
不好意思，命令打错了，是 pmap，目前暂时换了个自己封装的mysqli类，等会用remove方式试试，谢谢了
